-- MOVED: the canonical, current schema lives at /supabase/schema.sql (repo root).
-- This file was an earlier draft that predates the products/orders/site_content/
-- media_assets tables and catalog-v2 columns -- do not use it.
